export const AllProducts = [
  {
    name: "Whole Wheat Flour",
    description:
      "Premium whole wheat flour made from freshly milled grains, ideal for baking bread, cakes, and pastries. This flour is high in fiber and nutrients, ensuring you get a healthy and delicious product. Suitable for various dietary preferences and perfect for creating wholesome meals at home. Great for commercial or home use, and it comes in secure packaging to maintain freshness and quality. This product is trusted by bakers and chefs alike, and it guarantees excellent results every time.",
    categoryId: "031d0ef4-2fda-4e38-921a-630237da8242",
    unit: "kg",
    quantity: 50,
    unitWeight: "2 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "18, Taiwo Street, Ajegunle, Lagos",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/ti4uz330CwU",
      "https://unsplash.com/photos/IQ1kOQTJrOQ",
      "https://unsplash.com/photos/QbkGwv3xtmQ",
      "https://unsplash.com/photos/xyDQNmT6vSs",
    ],
  },
  {
    name: "Chocolate Chip Cookies",
    description:
      "Crunchy and delicious chocolate chip cookies made with the finest ingredients. Perfect for snacking, these cookies offer a delightful burst of chocolate in every bite. Great for tea time or as an on-the-go treat, they are loved by both kids and adults alike. Carefully baked to perfection, each cookie has a satisfying texture and flavor that melts in your mouth. Packed in resealable boxes to maintain freshness, these cookies make a fantastic gift or a simple indulgence at home.",
    categoryId: "031d0ef4-2fda-4e38-921a-630237da8242",
    unit: "box",
    quantity: 100,
    unitWeight: "500 g",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "22, Unity Road, Ikeja, Lagos",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/xyDQNmT6vSs",
      "https://unsplash.com/photos/agnhLQWqr1Q",
      "https://unsplash.com/photos/iRyGmA_no2Q",
      "https://unsplash.com/photos/ICW6QYOcdlg",
    ],
  },
  {
    name: "Sesame Seeds",
    description:
      "High-quality sesame seeds that are perfect for baking, cooking, or adding a nutritional boost to your meals. These seeds are packed with essential nutrients, including calcium, iron, and magnesium. Great for making tahini or sprinkling on bread and salads. The seeds are meticulously cleaned and sorted to ensure purity and quality. They have a rich nutty flavor that enhances the taste of dishes and baked goods, making them a must-have in any kitchen.",
    categoryId: "031d0ef4-2fda-4e38-921a-630237da8242",
    unit: "kg",
    quantity: 75,
    unitWeight: "1 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "45, Independence Avenue, GRA, Kaduna",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/mR_HR8NZwg8",
      "https://unsplash.com/photos/qVj3KuEikvg",
      "https://unsplash.com/photos/D76DklsG-5U",
      "https://unsplash.com/photos/8hgm6mKK04U",
    ],
  },
  {
    name: "Urea Fertilizer",
    description:
      "Top-grade urea fertilizer for enhancing soil fertility and ensuring optimal crop yield. This fertilizer is ideal for a wide variety of crops and is trusted by farmers for its efficiency and reliability. Comes in eco-friendly packaging for safe handling and storage. It dissolves easily in water, making it suitable for various application methods, including spray, drip irrigation, and soil application. A perfect solution for modern farming needs.",
    categoryId: "031d0ef4-2fda-4e38-921a-630237da8242",
    unit: "bag",
    quantity: 40,
    unitWeight: "50 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "12, Kano Street, Kano City, Kano",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/tvicgTdh7Fg",
      "https://unsplash.com/photos/-kEr-QltARg",
      "https://unsplash.com/photos/PFZTiiJnjag",
      "https://unsplash.com/photos/63qfL0TciY8",
    ],
  },
  {
    name: "Jute Bags",
    description:
      "Durable and eco-friendly jute bags suitable for packaging agricultural products like grains, seeds, and flour. These bags are biodegradable and offer excellent storage options while maintaining product quality during transportation and storage. Crafted with reinforced stitching to handle heavy loads, they provide a reliable solution for bulk packaging needs. The bags are also reusable, making them a sustainable choice for environmentally conscious users.",
    categoryId: "031d0ef4-2fda-4e38-921a-630237da8242",
    unit: "piece",
    quantity: 500,
    unitWeight: "1 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "50, Aba Road, Port Harcourt, Rivers",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/V0yAek6BgGk",
      "https://unsplash.com/photos/znM0ujn2RUA",
      "https://unsplash.com/photos/PzPbh-faPgU",
      "https://unsplash.com/photos/SyBYM8R6VU4",
    ],
  },
  {
    name: "Shovel",
    description:
      "Sturdy and ergonomic shovel for digging, lifting, and moving soil. Ideal for both small-scale gardening and large-scale farming projects. Made with high-quality materials for durability and ease of use. The shovel features a comfortable handle and a sharp blade that cuts through soil effortlessly. Whether you are planting, landscaping, or clearing debris, this tool is designed to handle it all with precision and reliability.",
    categoryId: "031d0ef4-2fda-4e38-921a-630237da8242",
    unit: "piece",
    quantity: 100,
    unitWeight: "3 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "67, Effurun Roundabout, Warri, Delta",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/asrWX-lU3RE",
      "https://unsplash.com/photos/A6S-q3D67Ss",
      "https://unsplash.com/photos/tAKXap853rY",
      "https://unsplash.com/photos/JbeBraLha7U",
    ],
  },
  {
    name: "Leather Gloves",
    description:
      "Protective leather gloves designed for agricultural work. These gloves provide excellent grip and protection from sharp tools and harmful substances. Durable and comfortable, they are an essential tool for farmers and gardeners. The gloves are crafted with breathable materials to prevent sweating, ensuring long-lasting comfort even during extended use. Perfect for heavy-duty tasks like pruning, weeding, and digging.",
    categoryId: "3b5c1da0-af21-4bf9-9213-26b8cbcba571",
    unit: "pair",
    quantity: 200,
    unitWeight: "500 g",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "30, Iwo Road, Ibadan, Oyo",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/2FrX56QL7P8",
      "https://unsplash.com/photos/xPfj_Kdcal4",
      "https://unsplash.com/photos/_DA3D5P71qs",
      "https://unsplash.com/photos/umLpP7uCZs0",
    ],
  },
  {
    name: "Live Chickens",
    description:
      "Healthy and well-bred live chickens suitable for meat and egg production. Raised in hygienic environments with proper care, these chickens offer premium quality and taste. Perfect for poultry farmers and household consumption. Each chicken is vaccinated and checked for health, ensuring a robust and disease-free stock. Ideal for enhancing the productivity of your poultry farm or fulfilling personal dietary needs.",
    categoryId: "3b5c1da0-af21-4bf9-9213-26b8cbcba571",
    unit: "bird",
    quantity: 150,
    unitWeight: "3 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "14, Orlu Road, Owerri, Imo",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/oSf8ePoG9NU",
      "https://unsplash.com/photos/LBI7cgq3pbM",
      "https://unsplash.com/photos/N-1XGL54pQg",
      "https://unsplash.com/photos/R1E6x8U83Ho",
    ],
  },
  {
    name: "Cucumber",
    description:
      "Freshly harvested cucumbers that are perfect for salads, sandwiches, and healthy snacks. These cucumbers are grown organically and are rich in vitamins and hydration. Great for refreshing summer recipes or juicing. Packed with care to ensure they retain their natural crispness and flavor, they are a healthy addition to any meal.",
    categoryId: "3b5c1da0-af21-4bf9-9213-26b8cbcba571",
    unit: "kg",
    quantity: 80,
    unitWeight: "1 kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "88, Ahmadu Bello Way, Victoria Island, Lagos",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/mR_HR8NZwg8",
      "https://unsplash.com/photos/BbQLHCpVUqA",
      "https://unsplash.com/photos/_WiFMBRT7Aw",
      "https://unsplash.com/photos/mR_HR8NZwg8",
    ],
  },
  {
    name: "Wheat Flour",
    description:
      "Premium wheat flour, ideal for baking bread, cakes, and other pastries. This finely milled flour ensures a smooth texture and excellent taste in all your culinary creations. Packed in a 25kg bag to meet both small-scale and commercial needs. Sourced from organic wheat farms for quality assurance.",
    categoryId: "3b5c1da0-af21-4bf9-9213-26b8cbcba571",
    unit: "kg",
    quantity: 100,
    unitWeight: "25kg",
    sellerId: "04c88a42-f5af-4afd-a510-1a0d61ded753",
    location: "18, Taiwo Street, Ajegunle, Lagos",
    regionId: "020aef55-dc8b-4a7c-98da-89c429f27419",
    images: [
      "https://unsplash.com/photos/dYshDcTI1Js",
      "https://unsplash.com/photos/xyDQNmT6vSs",
      "https://unsplash.com/photos/YvYBOSiBJE8",
      "https://unsplash.com/photos/du_OrQAA4r0",
    ],
  },
  {
    name: "Chocolate Chip Cookies",
    description:
      "Delicious chocolate chip cookies made with the finest ingredients. Each cookie is packed with rich chocolate chips, offering a perfect balance of crunchiness and sweetness. Ideal as a snack for any time of the day. Comes in a 500g resealable pack to maintain freshness.",
    categoryId: "3b5c1da0-af21-4bf9-9213-26b8cbcba571",
    unit: "g",
    quantity: 200,
    unitWeight: "500g",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "046d727b-3d64-4a56-85f3-ee3317454b5f",
    location: "5, Iweka Road, Onitsha, Anambra",
    images: [
      "https://unsplash.com/photos/Y2PYfopoz-k",
      "https://unsplash.com/photos/-XA-fTYYfV0",
      "https://unsplash.com/photos/SyBYM8R6VU4",
      "https://unsplash.com/photos/gkT4FfgHO5o",
    ],
  },
  {
    name: "Maize Seeds",
    description:
      "High-quality maize seeds with excellent germination rates. Perfect for farmers looking to achieve high yields. Resistant to pests and suitable for various soil types. Packed in 5kg bags for convenience and ease of use. Suitable for both large-scale and small-scale farming.",
    categoryId: "3b5c1da0-af21-4bf9-9213-26b8cbcba571",
    unit: "kg",
    quantity: 150,
    unitWeight: "5kg",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "046d727b-3d64-4a56-85f3-ee3317454b5f",
    location: "22, Old Market Road, Aba, Abia",
    images: [
      "https://unsplash.com/photos/ti4uz330CwU",
      "https://unsplash.com/photos/xPfj_Kdcal4",
      "https://unsplash.com/photos/v9eNihIWh8k",
      "https://unsplash.com/photos/ywiAen4L4qA",
    ],
  },
  {
    name: "Nitrate Fertilizer",
    description:
      "Highly effective urea fertilizer designed to boost crop growth and increase yields. This nitrogen-rich fertilizer is suitable for a wide range of crops, including maize, rice, and vegetables. Supplied in 50kg bags to support both smallholder and commercial farmers.",
    categoryId: "6c6ab193-16ce-4618-9c1b-4e89fd06a4ea",
    unit: "kg",
    quantity: 120,
    unitWeight: "50kg",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "046d727b-3d64-4a56-85f3-ee3317454b5f",
    location: "14, Unity Avenue, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/KSyemQIWwP8",
      "https://unsplash.com/photos/87TJNWkepvI",
      "https://unsplash.com/photos/A88emaZe7d8",
      "https://unsplash.com/photos/zZvsEMPxjIA",
    ],
  },
  {
    name: "Honey Packaging Jars",
    description:
      "Durable and transparent honey packaging jars with secure lids. Perfect for storing and selling honey, jams, and syrups. Each jar has a capacity of 1 liter, making it ideal for commercial packaging. Comes in a pack of 50 jars.",
    categoryId: "6c6ab193-16ce-4618-9c1b-4e89fd06a4ea",
    unit: "pack",
    quantity: 50,
    unitWeight: "50 jars",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "046d727b-3d64-4a56-85f3-ee3317454b5f",
    location: "7, Palm Road, Akure, Ondo",
    images: [
      "https://unsplash.com/photos/lp0IFw6YqZg",
      "https://unsplash.com/photos/oFAVqfTSby8",
      "https://unsplash.com/photos/xDrxJCdedcI",
      "https://unsplash.com/photos/OODWPtfXAF0",
    ],
  },
  {
    name: "Irrigation Sprinklers",
    description:
      "Efficient irrigation sprinklers designed to provide uniform water distribution. Ideal for vegetable gardens, lawns, and large-scale farms. Made from high-quality materials to ensure durability. Each pack contains three sprinklers with adjustable spray patterns.",
    categoryId: "6c6ab193-16ce-4618-9c1b-4e89fd06a4ea",
    unit: "pack",
    quantity: 80,
    unitWeight: "3 sprinklers per pack",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "046d727b-3d64-4a56-85f3-ee3317454b5f",
    location: "25, Market Street, Kano",
    images: [
      "https://unsplash.com/photos/Acfgb7bc-Bc",
      "https://unsplash.com/photos/baRYCsjO6z4",
      "https://unsplash.com/photos/WO4bxwzHRe8",
      "https://unsplash.com/photos/OxzhYtL-00Y",
    ],
  },
  {
    name: "Steel Grain Storage Silos",
    description:
      "Robust and durable steel grain storage silos designed to keep grains safe from pests and weather. Each silo has a capacity of 5 tons and is easy to assemble. Perfect for storing maize, rice, and other grains. Comes with a warranty for peace of mind.",
    categoryId: "6c6ab193-16ce-4618-9c1b-4e89fd06a4ea",
    unit: "ton",
    quantity: 20,
    unitWeight: "5 tons",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "06e436d8-f41c-4865-9d28-3b541721505f",
    location: "19, Agbaje Street, Kaduna",
    images: [
      "https://unsplash.com/photos/Dl6jeyfihLk",
      "https://unsplash.com/photos/rf-0DQu5M6Y",
      "https://unsplash.com/photos/I_9ILwtsl_k",
      "https://unsplash.com/photos/mR_HR8NZwg8",
    ],
  },
  {
    name: "Manual Weeders",
    description:
      "Ergonomic manual weeders for efficient removal of weeds from farms and gardens. Designed for comfort and ease of use, reducing strain during long hours of work. Each weeder is lightweight and made from rust-resistant materials.",
    categoryId: "6c6ab193-16ce-4618-9c1b-4e89fd06a4ea",
    unit: "piece",
    quantity: 100,
    unitWeight: "1kg per weeder",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "06e436d8-f41c-4865-9d28-3b541721505f",
    location: "8, Adegoke Close, Enugu",
    images: [
      "https://unsplash.com/photos/4yzPVohNuVI",
      "https://unsplash.com/photos/xlAmGyZE7Zg",
      "https://unsplash.com/photos/fTKetYpEKNQ",
      "https://unsplash.com/photos/pwaaqfoMibI",
    ],
  },
  {
    name: "Wheat Flour",
    description:
      "Premium wheat flour, ideal for baking bread, cakes, and other pastries. This finely milled flour ensures a smooth texture and excellent taste in all your culinary creations. Packed in a 25kg bag to meet both small-scale and commercial needs. Sourced from organic wheat farms for quality assurance.",
    categoryId: "6c6ab193-16ce-4618-9c1b-4e89fd06a4ea",
    unit: "kg",
    quantity: 100,
    unitWeight: "25kg",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "06e436d8-f41c-4865-9d28-3b541721505f",
    location: "18, Taiwo Street, Ajegunle, Lagos",
    images: [
      "https://unsplash.com/photos/knYQ6arClBE",
      "https://unsplash.com/photos/CtkDsu4w-Rs",
      "https://unsplash.com/photos/87TJNWkepvI",
      "https://unsplash.com/photos/jrzvClypPq8",
    ],
  },
  {
    name: "Vanilla Chip Cookies",
    description:
      "Delicious chocolate chip cookies made with the finest ingredients. Each cookie is packed with rich chocolate chips, offering a perfect balance of crunchiness and sweetness. Ideal as a snack for any time of the day. Comes in a 500g resealable pack to maintain freshness.",
    categoryId: "92c60935-0cfd-4730-8076-c4f9c8a115bc",
    unit: "g",
    quantity: 200,
    unitWeight: "500g",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "06e436d8-f41c-4865-9d28-3b541721505f",
    location: "5, Iweka Road, Onitsha, Anambra",
    images: [
      "https://unsplash.com/photos/BjelfpszQDw",
      "https://unsplash.com/photos/fTKetYpEKNQ",
      "https://unsplash.com/photos/gkT4FfgHO5o",
      "https://unsplash.com/photos/tCICLJ5ktBE",
    ],
  },
  {
    name: "Maize Seeds",
    description:
      "High-quality maize seeds with excellent germination rates. Perfect for farmers looking to achieve high yields. Resistant to pests and suitable for various soil types. Packed in 5kg bags for convenience and ease of use. Suitable for both large-scale and small-scale farming.",
    categoryId: "92c60935-0cfd-4730-8076-c4f9c8a115bc",
    unit: "kg",
    quantity: 150,
    unitWeight: "5kg",
    sellerId: "0090cdf5-4260-46fd-b87a-1f21a422e157",
    regionId: "06e436d8-f41c-4865-9d28-3b541721505f",
    location: "22, Old Market Road, Aba, Abia",
    images: [
      "https://unsplash.com/photos/t1mqA3V3-7g",
      "https://unsplash.com/photos/KSyemQIWwP8",
      "https://unsplash.com/photos/tvicgTdh7Fg",
      "https://unsplash.com/photos/BbQLHCpVUqA",
    ],
  },
  {
    name: "Organic Fertilizer",
    description:
      "Highly effective urea fertilizer designed to boost crop growth and increase yields. This nitrogen-rich fertilizer is suitable for a wide range of crops, including maize, rice, and vegetables. Supplied in 50kg bags to support both smallholder and commercial farmers.",
    categoryId: "92c60935-0cfd-4730-8076-c4f9c8a115bc",
    unit: "kg",
    quantity: 120,
    unitWeight: "50kg",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "06e436d8-f41c-4865-9d28-3b541721505f",
    location: "14, Unity Avenue, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/A6S-q3D67Ss",
      "https://unsplash.com/photos/fj0tFloTPGQ",
      "https://unsplash.com/photos/BwgKUh9tN84",
      "https://unsplash.com/photos/cSe3oKQ03OQ",
    ],
  },
  {
    name: "Honey Packaging Jars",
    description:
      "Durable and transparent honey packaging jars with secure lids. Perfect for storing and selling honey, jams, and syrups. Each jar has a capacity of 1 liter, making it ideal for commercial packaging. Comes in a pack of 50 jars.",
    categoryId: "92c60935-0cfd-4730-8076-c4f9c8a115bc",
    unit: "pack",
    quantity: 50,
    unitWeight: "50 jars",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "087a877d-7c85-4bf6-a45a-2177ae1299f5",
    location: "7, Palm Road, Akure, Ondo",
    images: [
      "https://unsplash.com/photos/J8k-gzI0Zy0",
      "https://unsplash.com/photos/cZhUxIQjILg",
      "https://unsplash.com/photos/tCICLJ5ktBE",
      "https://unsplash.com/photos/Ven2CV8IJ5A",
    ],
  },
  {
    name: "Irrigation Sprinklers",
    description:
      "Efficient irrigation sprinklers designed to provide uniform water distribution. Ideal for vegetable gardens, lawns, and large-scale farms. Made from high-quality materials to ensure durability. Each pack contains three sprinklers with adjustable spray patterns.",
    categoryId: "92c60935-0cfd-4730-8076-c4f9c8a115bc",
    unit: "pack",
    quantity: 80,
    unitWeight: "3 sprinklers per pack",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "087a877d-7c85-4bf6-a45a-2177ae1299f5",
    location: "25, Market Street, Kano",
    images: [
      "https://unsplash.com/photos/fj0tFloTPGQ",
      "https://unsplash.com/photos/dYshDcTI1Js",
      "https://unsplash.com/photos/v9eNihIWh8k",
      "https://unsplash.com/photos/cSe3oKQ03OQ",
    ],
  },
  {
    name: "Steel Grain Storage Silos",
    description:
      "Robust and durable steel grain storage silos designed to keep grains safe from pests and weather. Each silo has a capacity of 5 tons and is easy to assemble. Perfect for storing maize, rice, and other grains. Comes with a warranty for peace of mind.",
    categoryId: "92c60935-0cfd-4730-8076-c4f9c8a115bc",
    unit: "ton",
    quantity: 20,
    unitWeight: "5 tons",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "087a877d-7c85-4bf6-a45a-2177ae1299f5",
    location: "19, Agbaje Street, Kaduna",
    images: [
      "https://unsplash.com/photos/ABDTiLqDhJA",
      "https://unsplash.com/photos/Cs4QZdHrHt4",
      "https://unsplash.com/photos/8hgm6mKK04U",
      "https://unsplash.com/photos/agnhLQWqr1Q",
    ],
  },
  {
    name: "Manual Weeders",
    description:
      "Ergonomic manual weeders for efficient removal of weeds from farms and gardens. Designed for comfort and ease of use, reducing strain during long hours of work. Each weeder is lightweight and made from rust-resistant materials.",
    categoryId: "72c494f9-bac5-4b45-b9e6-5a294df64d23",
    unit: "piece",
    quantity: 100,
    unitWeight: "1kg per weeder",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "087a877d-7c85-4bf6-a45a-2177ae1299f5",
    location: "8, Adegoke Close, Enugu",
    images: [
      "https://unsplash.com/photos/Ven2CV8IJ5A",
      "https://unsplash.com/photos/LBI7cgq3pbM",
      "https://unsplash.com/photos/NYDo21ssGao",
      "https://unsplash.com/photos/4f7r1LuPYj8",
    ],
  },
  {
    name: "Farm Gloves",
    description:
      "Protective farm gloves made from durable materials to ensure safety while handling tools and farm equipment. Designed to offer comfort and flexibility during use. Available in various sizes to suit all hand types.",
    categoryId: "72c494f9-bac5-4b45-b9e6-5a294df64d23",
    unit: "pair",
    quantity: 300,
    unitWeight: "250g per pair",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "087a877d-7c85-4bf6-a45a-2177ae1299f5",
    location: "12, Amaechi Street, Port Harcourt, Rivers",
    images: [
      "https://unsplash.com/photos/kxqvE41_07k",
      "https://unsplash.com/photos/V0yAek6BgGk",
      "https://unsplash.com/photos/ywiAen4L4qA",
      "https://unsplash.com/photos/pJILiyPdrXI",
    ],
  },
  {
    name: "Broiler Chickens",
    description:
      "Healthy and fast-growing broiler chickens ideal for meat production. These chickens are raised in optimal conditions to ensure high-quality meat. Available at various growth stages to meet diverse needs.",
    categoryId: "72c494f9-bac5-4b45-b9e6-5a294df64d23",
    unit: "bird",
    quantity: 500,
    unitWeight: "2kg per bird",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "087a877d-7c85-4bf6-a45a-2177ae1299f5",
    location: "15, Gwarzo Road, Zaria, Kaduna",
    images: [
      "https://unsplash.com/photos/ABDTiLqDhJA",
      "https://unsplash.com/photos/ywiAen4L4qA",
      "https://unsplash.com/photos/DwTZwZYi9Ww",
      "https://unsplash.com/photos/llYg8Ni43fc",
    ],
  },
  {
    name: "Goat Feed",
    description:
      "Premium goat feed designed to provide balanced nutrition for optimal growth and productivity. Packed with essential vitamins and minerals to keep your livestock healthy. Comes in a 50kg bag and is suitable for all breeds of goats.",
    categoryId: "72c494f9-bac5-4b45-b9e6-5a294df64d23",
    unit: "kg",
    quantity: 200,
    unitWeight: "50kg",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "32, Opebi Road, Ikeja, Lagos",
    images: [
      "https://unsplash.com/photos/llYg8Ni43fc",
      "https://unsplash.com/photos/0EjvnhOkPLM",
      "https://unsplash.com/photos/znM0ujn2RUA",
      "https://unsplash.com/photos/uDUiRS8YroY",
    ],
  },
  {
    name: "Packaging Tapes",
    description:
      "High-quality packaging tapes suitable for securing cartons, bags, and other packaging materials. These tapes are strong and durable, ensuring that your goods are well-protected during storage and transit. Each roll measures 50 meters and is easy to use.",
    categoryId: "72c494f9-bac5-4b45-b9e6-5a294df64d23",
    unit: "roll",
    quantity: 500,
    unitWeight: "50m per roll",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "14, Aba-Owerri Road, Aba, Abia",
    images: [
      "https://unsplash.com/photos/qVj3KuEikvg",
      "https://unsplash.com/photos/y83Je1OC6Wc",
      "https://unsplash.com/photos/6qORI5j_6n8",
      "https://unsplash.com/photos/ThJIf6Q0b2s",
    ],
  },
  {
    name: "Frozen Fish Fillets",
    description:
      "Freshly frozen fish fillets packed with nutrients and flavor. These fillets are carefully processed to retain freshness and are perfect for grilling, frying, or baking. Each pack contains 1kg of fish fillets and is vacuum-sealed for longevity.",
    categoryId: "72c494f9-bac5-4b45-b9e6-5a294df64d23",
    unit: "kg",
    quantity: 300,
    unitWeight: "1kg",
    sellerId: "3bc64b8a-6c6e-4c35-83af-59b2a217fd4d",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "7, Ajose Adeogun Street, Victoria Island, Lagos",
    images: [
      "https://unsplash.com/photos/vCqmY3bfqfo",
      "https://unsplash.com/photos/FC9mIjVT-Yw",
      "https://unsplash.com/photos/2SfRAWkinpU",
      "https://unsplash.com/photos/agnhLQWqr1Q",
    ],
  },
  {
    name: "Granola Cereal",
    description:
      "Crunchy and delicious granola cereal made with oats, nuts, and dried fruits. Perfect for a healthy breakfast or snack. Each pack weighs 500g and is resealable to keep the contents fresh. Ideal for health-conscious individuals.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "g",
    quantity: 150,
    unitWeight: "500g",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "18, Garki Market, Abuja",
    images: [
      "https://unsplash.com/photos/Cs4QZdHrHt4",
      "https://unsplash.com/photos/87TJNWkepvI",
      "https://unsplash.com/photos/p-bkdO43shE",
      "https://unsplash.com/photos/zZvsEMPxjIA",
    ],
  },
  {
    name: "Cashew Butter",
    description:
      "Rich and creamy cashew butter made from 100% roasted cashews. This butter is free from additives and preservatives, ensuring a natural and healthy spread. Packed in 250g jars, perfect for spreading on bread or using in recipes.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "g",
    quantity: 250,
    unitWeight: "250g",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "9, Aro Road, Abeokuta, Ogun",
    images: [
      "https://unsplash.com/photos/erTjj730fMk",
      "https://unsplash.com/photos/lp0IFw6YqZg",
      "https://unsplash.com/photos/tVIqMgGlAG0",
      "https://unsplash.com/photos/muC_6gTMLR4",
    ],
  },
  {
    name: "Herbal Tea Mix",
    description:
      "A soothing blend of natural herbs and spices, this herbal tea mix is perfect for relaxation and boosting immunity. Each box contains 20 tea bags with no artificial flavors or additives. Ideal for tea lovers seeking a healthy alternative.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "box",
    quantity: 100,
    unitWeight: "20 tea bags",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "25, Alaba Market, Ojo, Lagos",
    images: [
      "https://unsplash.com/photos/xjXz8GKXcTI",
      "https://unsplash.com/photos/knYQ6arClBE",
      "https://unsplash.com/photos/2wugfiddtXw",
      "https://unsplash.com/photos/8Zt0xOOK4nI",
    ],
  },
  {
    name: "Organic Carrots",
    description:
      "Fresh and organically grown carrots harvested directly from local farms. These carrots are rich in vitamins and perfect for juicing, cooking, or eating raw. Sold in 5kg bundles, ensuring freshness and affordability.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "kg",
    quantity: 120,
    unitWeight: "5kg",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "038e5e11-67c5-4761-8f43-43c3b565a338",
    location: "3, Ijebu-Ode Road, Sagamu, Ogun",
    images: [
      "https://unsplash.com/photos/_WiFMBRT7Aw",
      "https://unsplash.com/photos/d-Cr8MEW5Uc",
      "https://unsplash.com/photos/JabLtzJl8bc",
      "https://unsplash.com/photos/ThJIf6Q0b2s",
    ],
  },
  {
    name: "Whole Wheat Bread",
    description:
      "Soft and nutritious whole wheat bread baked fresh daily. Made with 100% whole wheat flour, this bread is high in fiber and perfect for a healthy diet. Each loaf weighs 1kg and is carefully packed to preserve freshness.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "loaf",
    quantity: 250,
    unitWeight: "1kg",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "0c0e78eb-379b-4b03-84a5-06af28a10484",
    location: "6, Zik Avenue, Awka, Anambra",
    images: [
      "https://unsplash.com/photos/6xqAK6oAeHA",
      "https://unsplash.com/photos/eG3k60PrTGY",
      "https://unsplash.com/photos/Xne1N4yZuOY",
      "https://unsplash.com/photos/SyBYM8R6VU4",
    ],
  },
  {
    name: "Poultry Egg Crates",
    description:
      "Strong and reusable egg crates designed for safely storing and transporting eggs. Each crate holds up to 30 eggs and is made from high-quality, durable materials. Perfect for poultry farmers and distributors.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "crate",
    quantity: 300,
    unitWeight: "500g per crate",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "0c0e78eb-379b-4b03-84a5-06af28a10484",
    location: "11, Nnewi Road, Onitsha, Anambra",
    images: [
      "https://unsplash.com/photos/R1E6x8U83Ho",
      "https://unsplash.com/photos/6qORI5j_6n8",
      "https://unsplash.com/photos/OxzhYtL-00Y",
      "https://unsplash.com/photos/2fl-ocJ5MOA",
    ],
  },
  {
    name: "Natural Yogurt",
    description:
      "Creamy and delicious natural yogurt made from fresh milk. This yogurt is free from preservatives and artificial sweeteners, offering a healthy and nutritious snack. Available in 1-liter tubs for family use.",
    categoryId: "625a0ffa-8ffb-4f94-8dbb-a39900b80047",
    unit: "liter",
    quantity: 180,
    unitWeight: "1L",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "0c0e78eb-379b-4b03-84a5-06af28a10484",
    location: "10, Eleyele Road, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/k7bQqdUf954",
      "https://unsplash.com/photos/Qo51KwK1dKg",
      "https://unsplash.com/photos/xS_RzdD5CFE",
      "https://unsplash.com/photos/2wugfiddtXw",
    ],
  },
  {
    name: "Organic Tomatoes",
    description:
      "Freshly harvested organic tomatoes grown without synthetic pesticides or fertilizers. These tomatoes are rich in flavor and perfect for making sauces, salads, or stews. Sold in 5kg cartons to ensure bulk convenience for consumers and vendors.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "kg",
    quantity: 150,
    unitWeight: "5kg",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "0c0e78eb-379b-4b03-84a5-06af28a10484",
    location: "21, Uyo Road, Uyo, Akwa Ibom",
    images: [
      "https://unsplash.com/photos/knYQ6arClBE",
      "https://unsplash.com/photos/R1E6x8U83Ho",
      "https://unsplash.com/photos/eG3k60PrTGY",
      "https://unsplash.com/photos/6J--NXulQCs",
    ],
  },
  {
    name: "Fresh Watermelon",
    description:
      "Juicy and sweet watermelons grown in Nigeria's fertile farmlands. Each watermelon is carefully harvested to ensure quality and freshness. Great for hydration and packed with nutrients. Sold individually, averaging 3-5kg per piece.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "piece",
    quantity: 80,
    unitWeight: "4kg",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "0c0e78eb-379b-4b03-84a5-06af28a10484",
    location: "12, GRA Road, Ilorin, Kwara",
    images: [
      "https://unsplash.com/photos/P7Lh0usGcuk",
      "https://unsplash.com/photos/WqK_xV_hbug",
      "https://unsplash.com/photos/pJILiyPdrXI",
      "https://unsplash.com/photos/eG3k60PrTGY",
    ],
  },
  {
    name: "Protective Gloves",
    description:
      "Durable protective gloves designed for farming and industrial work. These gloves are made of high-quality materials to protect hands from cuts, abrasions, and chemical exposure. Sold in packs of 10 pairs, ideal for farmers and laborers.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "pack",
    quantity: 500,
    unitWeight: "10 pairs per pack",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "0c0e78eb-379b-4b03-84a5-06af28a10484",
    location: "8, Ikotun Market Road, Ikotun, Lagos",
    images: [
      "https://unsplash.com/photos/d19by2PLaPc",
      "https://unsplash.com/photos/jrzvClypPq8",
      "https://unsplash.com/photos/agkblvPff5U",
      "https://unsplash.com/photos/LbS_k_c3BYA",
    ],
  },
  {
    name: "Dried Fish",
    description:
      "Premium-quality dried fish sourced from local fishermen. These fish are sun-dried to retain their natural flavors and nutrients. Ideal for traditional soups and stews. Packaged in 1kg bundles for easy storage and use.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "kg",
    quantity: 120,
    unitWeight: "1kg",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "15, Aba Road, Port Harcourt, Rivers",
    images: [
      "https://unsplash.com/photos/erTjj730fMk",
      "https://unsplash.com/photos/vCqmY3bfqfo",
      "https://unsplash.com/photos/2SfRAWkinpU",
      "https://unsplash.com/photos/4yzPVohNuVI",
    ],
  },
  {
    name: "Sweet Potatoes",
    description:
      "Freshly harvested sweet potatoes from local Nigerian farms. These tubers are rich in fiber, vitamins, and minerals, making them a healthy addition to any meal. Sold in 10kg sacks, perfect for households and businesses.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "kg",
    quantity: 200,
    unitWeight: "10kg",
    sellerId: "65680f8a-6f86-436a-b807-bb3c93b062f9",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "17, Kaduna Road, Zaria, Kaduna",
    images: [
      "https://unsplash.com/photos/IoCWq07GaG4",
      "https://unsplash.com/photos/jVb0mSn0LbE",
      "https://unsplash.com/photos/KR2mdHJ5qMg",
      "https://unsplash.com/photos/R1E6x8U83Ho",
    ],
  },
  {
    name: "Whole Chicken",
    description:
      "Freshly processed whole chicken sourced from local poultry farms. These chickens are cleaned and packaged to maintain freshness and quality. Sold per bird, with an average weight of 2.5kg. Perfect for various culinary uses.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "bird",
    quantity: 100,
    unitWeight: "2.5kg",
    sellerId: "7b37470d-bb83-462f-8dea-a0ca691d9a22",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "22, Ogbomoso Road, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/jrzvClypPq8",
      "https://unsplash.com/photos/TuOiIpkIea8",
      "https://unsplash.com/photos/3HlgJNdnD7I",
      "https://unsplash.com/photos/d-Cr8MEW5Uc",
    ],
  },
  {
    name: "Cocoa Powder",
    description:
      "High-quality cocoa powder made from 100% pure cocoa beans. This cocoa powder is perfect for baking, making hot chocolate, and adding to smoothies. Sold in 1kg packs to meet both individual and commercial needs.",
    categoryId: "20ea0416-7afd-42a4-9e6f-524aa1428ed9",
    unit: "kg",
    quantity: 250,
    unitWeight: "1kg",
    sellerId: "7b37470d-bb83-462f-8dea-a0ca691d9a22",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "19, Cocoa House, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/7Vz3DtQDT3Q",
      "https://unsplash.com/photos/Hi9GSwWkCJk",
      "https://unsplash.com/photos/ABDTiLqDhJA",
      "https://unsplash.com/photos/P7Lh0usGcuk",
    ],
  },
  {
    name: "Milking Machine",
    description:
      "Efficient and durable milking machine designed for small to medium-sized dairy farms. This machine simplifies the milking process, saving time and effort while ensuring hygiene. Comes with a capacity of 25 liters per session.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "piece",
    quantity: 50,
    unitWeight: "25L capacity",
    sellerId: "7b37470d-bb83-462f-8dea-a0ca691d9a22",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "6, Ikorodu Road, Ketu, Lagos",
    images: [
      "https://unsplash.com/photos/xjXz8GKXcTI",
      "https://unsplash.com/photos/63qfL0TciY8",
      "https://unsplash.com/photos/6iat9p85VnQ",
      "https://unsplash.com/photos/agnhLQWqr1Q",
    ],
  },
  {
    name: "Farm Rake",
    description:
      "Strong and reliable farm rake designed for efficient clearing of leaves, grass, and debris. Made from high-quality metal with a sturdy wooden handle for comfort. Perfect for farmers and gardeners. Sold individually.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "piece",
    quantity: 200,
    unitWeight: "1.5kg",
    sellerId: "7b37470d-bb83-462f-8dea-a0ca691d9a22",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "5, Oyingbo Market, Lagos",
    images: [
      "https://unsplash.com/photos/6xqAK6oAeHA",
      "https://unsplash.com/photos/xjXz8GKXcTI",
      "https://unsplash.com/photos/pHM4a_RZSLE",
      "https://unsplash.com/photos/k7bQqdUf954",
    ],
  },
  {
    name: "Granulated Sugar",
    description:
      "Refined granulated sugar suitable for baking, sweetening beverages, and cooking. This sugar is pure, free-flowing, and comes in 50kg sacks. Ideal for households and commercial use in bakeries and restaurants.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "kg",
    quantity: 300,
    unitWeight: "50kg",
    sellerId: "83d0a32c-29c6-4d30-a0bb-1885c0c04bb8",
    regionId: "205e06bf-0c48-4a64-b7b4-492987d5b650",
    location: "8, Jibowu Street, Yaba, Lagos",
    images: [
      "https://unsplash.com/photos/rf-0DQu5M6Y",
      "https://unsplash.com/photos/wSb8d-ke5-4",
      "https://unsplash.com/photos/tvicgTdh7Fg",
      "https://unsplash.com/photos/llYg8Ni43fc",
    ],
  },
  {
    name: "Organic Tomatoes",
    description:
      "Freshly harvested organic tomatoes grown without synthetic pesticides or fertilizers. These tomatoes are rich in flavor and perfect for making sauces, salads, or stews. Sold in 5kg cartons to ensure bulk convenience for consumers and vendors.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "kg",
    quantity: 150,
    unitWeight: "5kg",
    sellerId: "83d0a32c-29c6-4d30-a0bb-1885c0c04bb8",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "21, Uyo Road, Uyo, Akwa Ibom",
    images: [
      "https://unsplash.com/photos/xyDQNmT6vSs",
      "https://unsplash.com/photos/zZvsEMPxjIA",
      "https://unsplash.com/photos/Ps2n0rShqaM",
      "https://unsplash.com/photos/8Zt0xOOK4nI",
    ],
  },
  {
    name: "Fresh Watermelon",
    description:
      "Juicy and sweet watermelons grown in Nigeria's fertile farmlands. Each watermelon is carefully harvested to ensure quality and freshness. Great for hydration and packed with nutrients. Sold individually, averaging 3-5kg per piece.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "piece",
    quantity: 80,
    unitWeight: "4kg",
    sellerId: "83d0a32c-29c6-4d30-a0bb-1885c0c04bb8",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "12, GRA Road, Ilorin, Kwara",
    images: [
      "https://unsplash.com/photos/BjelfpszQDw",
      "https://unsplash.com/photos/rlxZqmc6D_I",
      "https://unsplash.com/photos/eG3k60PrTGY",
      "https://unsplash.com/photos/FC9mIjVT-Yw",
    ],
  },
  {
    name: "Protective Gloves",
    description:
      "Durable protective gloves designed for farming and industrial work. These gloves are made of high-quality materials to protect hands from cuts, abrasions, and chemical exposure. Sold in packs of 10 pairs, ideal for farmers and laborers.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "pack",
    quantity: 500,
    unitWeight: "10 pairs per pack",
    sellerId: "83d0a32c-29c6-4d30-a0bb-1885c0c04bb8",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "8, Ikotun Market Road, Ikotun, Lagos",
    images: [
      "https://unsplash.com/photos/xPfj_Kdcal4",
      "https://unsplash.com/photos/HFbRnCjWHsk",
      "https://unsplash.com/photos/VLdaxYyXJvw",
      "https://unsplash.com/photos/Dl6jeyfihLk",
    ],
  },
  {
    name: "Dried Fish",
    description:
      "Premium-quality dried fish sourced from local fishermen. These fish are sun-dried to retain their natural flavors and nutrients. Ideal for traditional soups and stews. Packaged in 1kg bundles for easy storage and use.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "kg",
    quantity: 120,
    unitWeight: "1kg",
    sellerId: "83d0a32c-29c6-4d30-a0bb-1885c0c04bb8",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "15, Aba Road, Port Harcourt, Rivers",
    images: [
      "https://unsplash.com/photos/OokBLPrkCNk",
      "https://unsplash.com/photos/IoIbdFdGCnQ",
      "https://unsplash.com/photos/pFqrYbhIAXs",
      "https://unsplash.com/photos/V0yAek6BgGk",
    ],
  },
  {
    name: "Sweet Potatoes",
    description:
      "Freshly harvested sweet potatoes from local Nigerian farms. These tubers are rich in fiber, vitamins, and minerals, making them a healthy addition to any meal. Sold in 10kg sacks, perfect for households and businesses.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "kg",
    quantity: 200,
    unitWeight: "10kg",
    sellerId: "83d0a32c-29c6-4d30-a0bb-1885c0c04bb8",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "17, Kaduna Road, Zaria, Kaduna",
    images: [
      "https://unsplash.com/photos/fj0tFloTPGQ",
      "https://unsplash.com/photos/Osl4I3IS9Cw",
      "https://unsplash.com/photos/2FrX56QL7P8",
      "https://unsplash.com/photos/cZhUxIQjILg",
    ],
  },
  {
    name: "Whole Chicken",
    description:
      "Freshly processed whole chicken sourced from local poultry farms. These chickens are cleaned and packaged to maintain freshness and quality. Sold per bird, with an average weight of 2.5kg. Perfect for various culinary uses.",
    categoryId: "605b8ba8-ab06-45b0-b168-e65e483ef749",
    unit: "bird",
    quantity: 100,
    unitWeight: "2.5kg",
    sellerId: "897c97ae-987d-45de-9e3f-319f56953660",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "22, Ogbomoso Road, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/tCICLJ5ktBE",
      "https://unsplash.com/photos/xjXz8GKXcTI",
      "https://unsplash.com/photos/rf-0DQu5M6Y",
      "https://unsplash.com/photos/yZf1quatKCA",
    ],
  },
  {
    name: "Cocoa Powder",
    description:
      "High-quality cocoa powder made from 100% pure cocoa beans. This cocoa powder is perfect for baking, making hot chocolate, and adding to smoothies. Sold in 1kg packs to meet both individual and commercial needs.",
    categoryId: "76ad8be7-5ba2-497d-9ade-8a9a2180b5e1",
    unit: "kg",
    quantity: 250,
    unitWeight: "1kg",
    sellerId: "897c97ae-987d-45de-9e3f-319f56953660",
    regionId: "110ecd83-6c91-4fc0-afb8-12c5070354f7",
    location: "19, Cocoa House, Ibadan, Oyo",
    images: [
      "https://unsplash.com/photos/xII7efH1G6o",
      "https://unsplash.com/photos/iJnZwLBOB1I",
      "https://unsplash.com/photos/qVj3KuEikvg",
      "https://unsplash.com/photos/CtkDsu4w-Rs",
    ],
  },
  {
    name: "Milking Machine",
    description:
      "Efficient and durable milking machine designed for small to medium-sized dairy farms. This machine simplifies the milking process, saving time and effort while ensuring hygiene. Comes with a capacity of 25 liters per session.",
    categoryId: "76ad8be7-5ba2-497d-9ade-8a9a2180b5e1",
    unit: "piece",
    quantity: 50,
    unitWeight: "25L capacity",
    sellerId: "897c97ae-987d-45de-9e3f-319f56953660",
    regionId: "2555134f-f8fe-4400-acfd-06929631cac3",
    location: "6, Ikorodu Road, Ketu, Lagos",
    images: [
      "https://unsplash.com/photos/qPJ6eRAMmCM",
      "https://unsplash.com/photos/muC_6gTMLR4",
      "https://unsplash.com/photos/pFqrYbhIAXs",
      "https://unsplash.com/photos/pJILiyPdrXI",
    ],
  },
  {
    name: "Farm Rake",
    description:
      "Strong and reliable farm rake designed for efficient clearing of leaves, grass, and debris. Made from high-quality metal with a sturdy wooden handle for comfort. Perfect for farmers and gardeners. Sold individually.",
    categoryId: "76ad8be7-5ba2-497d-9ade-8a9a2180b5e1",
    unit: "piece",
    quantity: 200,
    unitWeight: "1.5kg",
    sellerId: "897c97ae-987d-45de-9e3f-319f56953660",
    regionId: "2555134f-f8fe-4400-acfd-06929631cac3",
    location: "5, Oyingbo Market, Lagos",
    images: [
      "https://unsplash.com/photos/QxkBP3A9XmU",
      "https://unsplash.com/photos/agkblvPff5U",
      "https://unsplash.com/photos/ywiAen4L4qA",
      "https://unsplash.com/photos/kmF_Aq8gkp0",
    ],
  },
  {
    name: "Granulated Sugar",
    description:
      "Refined granulated sugar suitable for baking, sweetening beverages, and cooking. This sugar is pure, free-flowing, and comes in 50kg sacks. Ideal for households and commercial use in bakeries and restaurants.",
    categoryId: "76ad8be7-5ba2-497d-9ade-8a9a2180b5e1",
    unit: "kg",
    quantity: 300,
    unitWeight: "50kg",
    sellerId: "897c97ae-987d-45de-9e3f-319f56953660",
    regionId: "2555134f-f8fe-4400-acfd-06929631cac3",
    location: "8, Jibowu Street, Yaba, Lagos",
    images: [
      "https://unsplash.com/photos/Osl4I3IS9Cw",
      "https://unsplash.com/photos/1fpyA_z2woY",
      "https://unsplash.com/photos/agkblvPff5U",
      "https://unsplash.com/photos/Xne1N4yZuOY",
    ],
  },
];
