export const AllUsers = [
  {
    name: "Paul Miller",
    email: "user1@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh0001zwqs6p36nezzj",
    type: "wholesaler",
    address: "12 Adeola Odeku Street, Victoria Island, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    coverImg: "",
    phoneNumber: "+2348034567890",
  },
  {
    name: "Luke Jones",
    email: "user2@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz000fwqs69bhs9leo",
    type: "wholesaler",
    address: "45 Herbert Macaulay Way, Yaba, Lagos",
    avatar: "",
    coverImg: "https://picsum.photos/800/300?random=1",
    phoneNumber: "+2348123456789",
  },
  {
    name: "Olivia Miller",
    email: "user3@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz000fwqs69bhs9leo",
    type: "wholesaler",
    address: "18 Opebi Road, Ikeja, Lagos",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    coverImg: "https://picsum.photos/800/300?random=2",
    phoneNumber: "+2349056781234",
  },
  {
    name: "Sophia Miller",
    email: "user4@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz0013wqs61ey92bnc",
    type: "farmer",
    address: "7 Akin Adesola Street, Victoria Island, Lagos",
    avatar: "",
    coverImg: "",
    phoneNumber: "+2347012345678",
  },
  {
    name: "John Johnson",
    email: "user5@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh10035wqs64bbou1sq",
    type: "wholesaler",
    address: "22 Awolowo Road, Ikoyi, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    coverImg: "https://picsum.photos/800/300?random=3",
    phoneNumber: "+2348156789012",
  },
  {
    name: "Mark Martinez",
    email: "user6@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz000fwqs69bhs9leo",
    type: "farmer",
    address: "22 Awolowo Road, Ikoyi, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    coverImg: "",
    phoneNumber: "+2348167890123",
  },
  {
    name: "James Miller",
    email: "user7@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh0001zwqs6p36nezzj",
    type: "buyer",
    address: "14 Allen Avenue, Ikeja, Lagos",
    avatar: "",
    coverImg: "https://picsum.photos/800/300?random=4",
    phoneNumber: "+2348031234567",
  },
  {
    name: "Olivia Martinez",
    email: "user8@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh30061wqs6pfu3j6vw",
    type: "buyer",
    address: "9 Broad Street, Lagos Island, Lagos",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    coverImg: "",
    phoneNumber: "+2349023456789",
  },
  {
    name: "Sophia Hernandez",
    email: "user9@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz0013wqs61ey92bnc",
    type: "wholesaler",
    address: "56 Bode Thomas Street, Surulere, Lagos",
    avatar: "",
    coverImg: "https://picsum.photos/800/300?random=5",
    phoneNumber: "+2348039876543",
  },
  {
    name: "John Davis",
    email: "user10@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz0013wqs61ey92bnc",
    type: "buyer",
    address: "3 Mobolaji Bank Anthony Way, Maryland, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    coverImg: "",
    phoneNumber: "+2348154321987",
  },
  {
    name: "Olivia Jones",
    email: "user11@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz000fwqs69bhs9leo",
    type: "buyer",
    address: "7 Akin Adesola Street, Victoria Island, Lagos",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    coverImg: "https://picsum.photos/800/300?random=6",
    phoneNumber: "+2348076543210",
  },
  {
    name: "Liam Smith",
    email: "user12@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh4008bwqs6aqvaze8r",
    type: "farmer",
    address: "45 Herbert Macaulay Way, Yaba, Lagos",
    avatar: "",
    coverImg: "",
    phoneNumber: "+2348129876543",
  },
  {
    name: "Mark Martinez",
    email: "user13@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh10035wqs64bbou1sq",
    type: "buyer",
    address: "14 Allen Avenue, Ikeja, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    coverImg: "https://picsum.photos/800/300?random=7",
    phoneNumber: "+2349038765432",
  },
  {
    name: "John Hernandez",
    email: "user14@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz0013wqs61ey92bnc",
    type: "farmer",
    address: "12 Adeola Odeku Street, Victoria Island, Lagos",
    avatar: "",
    coverImg: "",
    phoneNumber: "+2348176543987",
  },
  {
    name: "Luke Martinez",
    email: "user15@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh0001zwqs6p36nezzj",
    type: "buyer",
    address: "18 Opebi Road, Ikeja, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    coverImg: "https://picsum.photos/800/300?random=8",
    phoneNumber: "+2349098765432",
  },
  {
    name: "John Brown",
    email: "user16@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh30061wqs6pfu3j6vw",
    type: "buyer",
    address: "12 Adeola Odeku Street, Victoria Island, Lagos",
    avatar: "",
    coverImg: "",
    phoneNumber: "+2348012345678",
  },
  {
    name: "John Davis",
    email: "user17@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh4008bwqs6aqvaze8r",
    type: "buyer",
    address: "56 Bode Thomas Street, Surulere, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    coverImg: "https://picsum.photos/800/300?random=9",
    phoneNumber: "+2348165432987",
  },
  {
    name: "Mark Jones",
    email: "user18@example.com",
    password: "Payboi10",
    regionId: "cme8ixzgz0013wqs61ey92bnc",
    type: "wholesaler",
    address: "22 Awolowo Road, Ikoyi, Lagos",
    avatar: "",
    coverImg: "",
    phoneNumber: "+2348067890123",
  },
  {
    name: "Mark Smith",
    email: "user19@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh0001zwqs6p36nezzj",
    type: "wholesaler",
    address: "9 Broad Street, Lagos Island, Lagos",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    coverImg: "https://picsum.photos/800/300?random=10",
    phoneNumber: "+2348023456789",
  },
  {
    name: "Olivia Hernandez",
    email: "user20@example.com",
    password: "Payboi10",
    regionId: "cme8ixzh0001zwqs6p36nezzj",
    type: "buyer",
    address: "7 Akin Adesola Street, Victoria Island, Lagos",
    avatar: "",
    coverImg: "",
    phoneNumber: "+2348109876543",
  },
];
